config/routes.rb
FacebookClone::Application.routes.draw do
  resource :session, :only => [:new, :create, :destroy]
  resources :users, :only => [:new, :create]

  namespace :api, defaults: { format: :json } do
    resource :guests, :only => [:create]
    resources :users, :only => [:index, :show, :update]
    resources :private_messages, :only => [:show, :index, :create]
    resources :friends, :only => [:index, :create, :destroy]
    resources :friend_requests, :only => [:index, :create]
    resources :posts, :only => [:index, :show, :create]
    resources :comments, :only => [:create]
    resources :friends_suggestions, :only => [:index]
  end
  root :to => "root#root"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FacebookClone</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', :media => 'all' %>
  <%= javascript_include_tag 'application' %>

  <%= stylesheet_link_tag '//netdna.bootstrapcdn.com/bootswatch/3.0.3/cosmo/bootstrap.min.css' %>

  <%= csrf_meta_tags %>
</head>
<body>

<div id="top-bar">
  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">OpenCommunicate</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     
      <% if logged_in? %>
        <ul class="nav navbar-nav">
          <li>
            <form id="search-form" 
                  class="navbar-form" 
                  role="search">
              <div class="form-group">
                <input id="search-bar"
                       type="text" 
                       class="form-control" 
                       placeholder="Search"
                       autofocus="autofocus">
              </div>
              <input type="submit" style="position: absolute; left: -9999px"/>
            </form>
          </li>
        </ul>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><a href="#"><span class="glyphicon glyphicon-home"></span></a>
          <li><a href="#messages"><span class="glyphicon glyphicon-envelope"></span></a>
          <li><a href="#friends"><span class="glyphicon glyphicon-user"></span></a>

          <li><a href="#" id="find-friends-button">Find Friends</a>

          <li><%= link_to current_user.name, "#users/#{current_user.id}" %>
          

          <li><a href="/session" data-method="delete"><span class='glyphicon glyphicon-log-out'></span></a>
        <% else %>
          <li><%= link_to "Sign In", new_session_url %>
          <li><%= link_to "Sign Up", new_user_url, class: "btn-link" %>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

<div class="row">

  <%= yield %>

  <% flash[:errors] && flash[:errors].each do |error| %>
    <%= error %><br>
  <% end %>

</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47830808-1', 'opencommunicate.com');
  ga('send', 'pageview');

</script>

</body>
</html>